package mycricketprobably;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ABCD
 */
public class interteampart extends javax.swing.JFrame {

    /**
     * Creates new form interteampart
     */
    String a,b,c,d,e,f,g,h,i,j,k,l;
    public interteampart() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox1.setText("India");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 37, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox2.setText("Australia");
        jInternalFrame1.getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 98, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox3.setText("South Africa");
        jInternalFrame1.getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 158, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox4.setText("England");
        jInternalFrame1.getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 224, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox5.setText("Sril Lanka");
        jInternalFrame1.getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 280, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox6.setText("Bangladesh");
        jInternalFrame1.getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 158, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox7.setText("Pakistan");
        jInternalFrame1.getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 37, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox8.setText("West Indies");
        jInternalFrame1.getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 98, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox9.setText("New Zealand");
        jInternalFrame1.getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 224, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox10.setText("Zimbabwe");
        jInternalFrame1.getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 280, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox11.setText("Ireland");
        jInternalFrame1.getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 336, -1, -1));

        jCheckBox12.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jCheckBox12.setText("Afghanistan");
        jInternalFrame1.getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 336, -1, -1));

        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 389, 428, 56));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycricketprobably/taj-mahal-sunrise_6724_600x450.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(jCheckBox1.isSelected())
        {
             a=jCheckBox1.getText();
        }
        if(jCheckBox2.isSelected())
        {
             b=jCheckBox2.getText();
        }
        if(jCheckBox3.isSelected())
        {
             c=jCheckBox3.getText();
        }
        if(jCheckBox4.isSelected())
        {
             d=jCheckBox4.getText();
        }
        if(jCheckBox5.isSelected())
        {
             e=jCheckBox5.getText();
        }
        if(jCheckBox6.isSelected())
        {
             f=jCheckBox6.getText();
        }
        if(jCheckBox7.isSelected())
        {
             g=jCheckBox7.getText();
        }
        if(jCheckBox8.isSelected())
        {
             h=jCheckBox8.getText();
        }
        if(jCheckBox9.isSelected())
        {
             i=jCheckBox9.getText();
        }
        if(jCheckBox10.isSelected())
        {
             j=jCheckBox10.getText();
        }
        if(jCheckBox11.isSelected())
        {
             k=jCheckBox11.getText();
        }
        if(jCheckBox12.isSelected())
        {
             l=jCheckBox12.getText();
        }
        international obj=new international(a,b,c,d,e,f,g,h,i,j,k,l);
        obj.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interteampart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interteampart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interteampart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interteampart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interteampart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
