package mycricketprobably;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */

public class mycricket extends javax.swing.JFrame {

    /**
     * Creates new form mycricket
     */
    private int score=0,wicket=0,over1=0,over2=0;
    Connection con;
    ResultSet rs,rs2;
    Statement st;
    String connectionURL="jdbc:mysql://localhost:3306/mycricket";
    Timer t;
    int loc=0;
    
    public mycricket() {
        initComponents();
        setLocationRelativeTo(null);
        functioncombo();
        Get_Data();
       
        jLabel30.setBounds(0,0,700,40);
         t=new Timer(10,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
           jLabel30.setBounds(loc,0,700,40); 
           loc=loc+1;
           int width=jPanel7.getWidth();
           if(loc>width)
           {
             loc=0;
            }
           System.out.println(width);
           
           
        }

            
        
                 
                 
    });
         t.start();
    }
    
    
    public void connection() throws ClassNotFoundException, SQLException
    {
      
           
            try
            {
            Class.forName("com.mysql.jdbc.Driver");
                        con=DriverManager.getConnection(connectionURL,"root","");
			st = con.createStatement();
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
       
    }
    
    private void functioncombo(){
        try{
            connection();
            rs=st.executeQuery("select * from members where team!='India'");
            while(rs.next()){
                String team=rs.getString("team");
                jComboBox1.addItem(team);
                //jComboBox2.addItem(team);
            }
            
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void Get_Data(){
        String sql="select opponent as 'Opponent Team', start as 'Match Date',venue as 'Venue',format as 'Match Format' from homefix order by start";
        try{
         connection();
            rs= st.executeQuery(sql);
         jTable5.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }
    
 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel6 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel9 = new javax.swing.JPanel();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton54 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel11 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycricketprobably/newhome.jpg"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 840, 450);

        jTabbedPane1.addTab("Home", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Team", "Board"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 500, 240);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Delete");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(210, 370, 220, 80);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Insert new");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(0, 370, 210, 80);

        jButton13.setBackground(new java.awt.Color(102, 102, 102));
        jButton13.setText("Refresh");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);
        jButton13.setBounds(630, 370, 210, 80);

        jButton55.setBackground(new java.awt.Color(102, 102, 102));
        jButton55.setText("Restore");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton55);
        jButton55.setBounds(430, 370, 210, 80);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycricketprobably/batsman.jpg"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(0, 0, 840, 450);

        jTabbedPane1.addTab("Members&Teams", jPanel3);

        jPanel4.setLayout(null);

        jTable2.setBackground(new java.awt.Color(102, 102, 102));
        jTable2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rank", "T20", "Rating3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(560, 80, 270, 260);

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setText("Bowler");
        jButton8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(170, 350, 170, 100);

        jButton27.setBackground(new java.awt.Color(102, 102, 102));
        jButton27.setText("Team");
        jButton27.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton27);
        jButton27.setBounds(340, 350, 160, 100);

        jButton28.setBackground(new java.awt.Color(102, 102, 102));
        jButton28.setText("View Top Teams");
        jButton28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton28);
        jButton28.setBounds(670, 350, 170, 100);

        jButton29.setBackground(new java.awt.Color(102, 102, 102));
        jButton29.setText("Batsman");
        jButton29.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton29);
        jButton29.setBounds(0, 350, 170, 100);

        jButton30.setBackground(new java.awt.Color(102, 102, 102));
        jButton30.setText("Manual Entry");
        jButton30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton30);
        jButton30.setBounds(500, 350, 170, 100);

        jLabel23.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setToolTipText("");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(90, 30, 110, 40);

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 0));
        jPanel4.add(jLabel24);
        jLabel24.setBounds(360, 20, 120, 50);

        jLabel28.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 0));
        jPanel4.add(jLabel28);
        jLabel28.setBounds(630, 20, 110, 50);

        jTable3.setBackground(new java.awt.Color(102, 102, 102));
        jTable3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rank", "Test", "Rating1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 80, 260, 260);

        jTable4.setBackground(new java.awt.Color(102, 102, 102));
        jTable4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rank", "ODI", "Rating2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(280, 80, 270, 260);

        jTabbedPane1.addTab("Rankings", jPanel4);

        jPanel5.setLayout(null);

        jInternalFrame3.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame3.setVisible(true);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Home fixture details"));

        jLabel27.setText("Opponent");

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Date");

        jLabel2.setText("Format");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Test", "ODI", "T20" }));

        jLabel3.setText("Venue");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton12.setText("Refresh");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton12))
                .addGap(20, 20, 20))
        );

        jLabel4.setText("Date");

        jButton11.setText("View  opponent fixture");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenu2.setText("Operations");

        jMenuItem2.setText("Edit Opponent fixture");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem8.setText("View fixture");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar2.add(jMenu2);

        jInternalFrame3.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.add(jInternalFrame3);
        jInternalFrame3.setBounds(0, 0, 840, 450);

        jTabbedPane1.addTab("Match Organizer", jPanel5);

        jPanel6.setLayout(null);

        jButton10.setBackground(new java.awt.Color(102, 102, 102));
        jButton10.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Domestic Events");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(600, 90, 240, 110);

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Select a New Team");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(440, 330, 390, 90);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Select an Existing Team");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(470, 200, 370, 120);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycricketprobably/cric.jpg"))); // NOI18N
        jPanel6.add(jLabel26);
        jLabel26.setBounds(0, 50, 840, 400);

        jInternalFrame1.setVisible(true);

        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuItem7.setText("Add new players");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar3.add(jMenu4);

        jInternalFrame1.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 840, 50);

        jTabbedPane1.addTab("Team Selection & Events", jPanel6);

        jInternalFrame6.setVisible(true);
        jInternalFrame6.getContentPane().setLayout(null);

        jSplitPane3.setDividerLocation(104);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel8.setBackground(new java.awt.Color(116, 136, 161));

        jComboBox7.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "India", "South Africa\t", "Sri Lanka\t", "Australia\t", "England\t", "Pakistan\t", "New Zealand\t", "West Indies\t", "Bangladesh\t", "Zimbabwe\t", "Afghanistan\t", "Ireland\t", " " }));

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel10.setText("Wickets");

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel12.setText("Run rate");

        jLabel13.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel15.setText("Overs");

        jButton54.setText("Refresh");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(".");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton54)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton54)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jSplitPane3.setTopComponent(jPanel8);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(204);

        jPanel11.setBackground(new java.awt.Color(190, 212, 242));
        jPanel11.setLayout(null);

        jButton26.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton26.setText("6R");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jButton26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton26KeyPressed(evt);
            }
        });
        jPanel11.add(jButton26);
        jButton26.setBounds(470, 100, 120, 70);

        jButton32.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton32.setText("Leg Bye");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jButton32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton32KeyPressed(evt);
            }
        });
        jPanel11.add(jButton32);
        jButton32.setBounds(0, 177, 118, 50);

        jButton33.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton33.setText("Bye");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jButton33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton33KeyPressed(evt);
            }
        });
        jPanel11.add(jButton33);
        jButton33.setBounds(124, 177, 113, 50);

        jButton34.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton34.setText("Wide");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jButton34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton34KeyPressed(evt);
            }
        });
        jPanel11.add(jButton34);
        jButton34.setBounds(243, 177, 103, 50);

        jButton35.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton35.setText("No Ball");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jButton35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton35KeyPressed(evt);
            }
        });
        jPanel11.add(jButton35);
        jButton35.setBounds(350, 180, 115, 50);

        jButton36.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton36.setText("1R");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jButton36.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton36KeyPressed(evt);
            }
        });
        jPanel11.add(jButton36);
        jButton36.setBounds(0, 106, 81, 60);

        jButton37.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton37.setText("2R");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jButton37.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton37KeyPressed(evt);
            }
        });
        jPanel11.add(jButton37);
        jButton37.setBounds(87, 106, 76, 60);

        jButton38.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton38.setText("3R");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jButton38.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton38KeyPressed(evt);
            }
        });
        jPanel11.add(jButton38);
        jButton38.setBounds(169, 106, 78, 60);

        jButton39.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton39.setText("4R");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jButton39.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton39KeyPressed(evt);
            }
        });
        jPanel11.add(jButton39);
        jButton39.setBounds(340, 106, 100, 60);

        jButton40.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton40.setText("5R");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jButton40.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton40KeyPressed(evt);
            }
        });
        jPanel11.add(jButton40);
        jButton40.setBounds(253, 106, 77, 60);

        jButton42.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton42.setText("Out!");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jButton42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton42KeyPressed(evt);
            }
        });
        jPanel11.add(jButton42);
        jButton42.setBounds(460, 180, 136, 50);

        jButton44.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton44.setText("CLEAR");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton44);
        jButton44.setBounds(220, 240, 170, 40);

        jButton45.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton45.setText("Win/Loss");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton45);
        jButton45.setBounds(400, 240, 170, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycricketprobably/sc.jpg"))); // NOI18N
        jPanel11.add(jLabel22);
        jLabel22.setBounds(0, 0, 600, 300);

        jSplitPane1.setRightComponent(jPanel11);

        jPanel12.setBackground(new java.awt.Color(51, 102, 0));

        jButton20.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton20.setText("Increment over");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jButton20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton20KeyPressed(evt);
            }
        });

        jButton23.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton23.setText("Roll back wicket");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton25.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton25.setText("OUT!");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jButton14.setText("Undo");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel12);

        jPanel10.add(jSplitPane1);

        jSplitPane3.setRightComponent(jPanel10);

        jInternalFrame6.getContentPane().add(jSplitPane3);
        jSplitPane3.setBounds(0, 0, 829, 759);

        jMenu1.setText("Edit");

        jMenuItem3.setText("Match Details");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Statistics");
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Interruption");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jInternalFrame6.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame6, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jInternalFrame6, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Scorecard", jPanel9);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 165, 850, 480);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top image.jpg"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 0, 1130, 190);

        jButton7.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton7.setText("What's new!");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(860, 330, 270, 50);

        jButton31.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton31.setText("Endorsements");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31);
        jButton31.setBounds(860, 370, 270, 50);

        jButton47.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton47.setText("Salary Management");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton47);
        jButton47.setBounds(860, 410, 270, 50);

        jButton48.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton48.setText("Credits");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton48);
        jButton48.setBounds(860, 530, 270, 40);

        jButton49.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton49.setText("Refresh");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton49);
        jButton49.setBounds(860, 290, 270, 50);

        jButton50.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton50.setText("FAQs");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton50);
        jButton50.setBounds(860, 450, 270, 50);

        jButton51.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton51.setText("Logout");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51);
        jButton51.setBounds(860, 560, 270, 50);

        jButton53.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jButton53.setText("About");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton53);
        jButton53.setBounds(860, 490, 270, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycricketprobably/newaddition.jpg"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(0, 150, 1130, 490);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Developed by  Jesseel Mugdhar,  Gautam Panickar S.S,  Gouri S,  Keerthi S.S");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 650, 1130, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        if(wicket<10)
        {
        wicket=wicket+1;
        jLabel11.setText(String.valueOf(wicket));
        }
        else
        {
           JOptionPane.showMessageDialog(null,"You have reached the maximum number of wickets!");
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        String a=jLabel11.getText();
        int b=Integer.parseInt(a);
        b--;
        wicket=b;
        jLabel11.setText(String.valueOf(b));
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
         tryform obj=new tryform();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
        jLabel9.setText(null);
        jLabel11.setText(null);
        jLabel13.setText(null);
        jLabel14.setText(null);
        jLabel20.setText(null);
        score=0;
        wicket=0;
        over1=0;
        over2=0;
        
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        
        if(wicket<10)
        {
        wicket=wicket+1;
        jLabel11.setText(String.valueOf(wicket));
        }
        else
        {
           JOptionPane.showMessageDialog(null,"You have reached the maximum number of wickets!");
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        
        score=score+5;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        
        score=score+4;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
       
        score=score+3;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        
        score=score+2;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        
        score=score+1;
        jLabel9.setText(String.valueOf(score));
        
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        score=score+1;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        score=score+1;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
       
        score=score+1;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        
        score=score+1;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        
        score=score+6;
        jLabel9.setText(String.valueOf(score));
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        domestic obj= new domestic();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        newteam obj=new newteam();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try
        {
            connection();
            rs=st.executeQuery("select * from members");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        con.close();
        }
        catch(ClassNotFoundException | SQLException ex) {
            Logger.getLogger(mycricket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        confirmins obj=new confirmins();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        confirmdel obj=new confirmdel();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        /*
        photogallery obj=new photogallery();
        obj.setVisible(true);
        */
        dispose();
        mc obj=new mc();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        //TODO add your handling code here:
        credits obj=new credits();
        obj.setVisible(true);
      
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
        restoration obj=new restoration();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        whatsnew obj=new whatsnew();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        Endorse obj=new Endorse();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
        salary obj=new salary();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
        about obj=new about();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
        String x= jLabel9.getText();
        String y= jLabel14.getText();
        float a=Float.parseFloat(x);
        float b=Float.parseFloat(y);
         float c;
        if(b!=0)
        {
           c= a/b;
           jLabel13.setText(String.valueOf(c));
        }
        else
        {
           c=0; 
            jLabel13.setText(String.valueOf(c));
        }
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        tryform obj=new tryform();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        prerankentry obj=new prerankentry();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        try
        {
            connection();
            rs=st.executeQuery("select rank,test,rating1 from testteamranking order by rating1 desc,rank asc");
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            rs=st.executeQuery("select rank,ODI,rating2 from ODIteamranking order by rating2 desc,rank asc");
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
            rs=st.executeQuery("select rank,T20,rating3 from T20teamranking order by rating3 desc,rank asc");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        
        con.close();
        }
        catch(ClassNotFoundException | SQLException ex) {
            Logger.getLogger(mycricket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        try
        {
            connection();
            rs=st.executeQuery("select test from testteamranking  where rank=1 ");
            rs.next();
            jLabel23.setText(rs.getString(1)); 
             rs=st.executeQuery("select ODI from ODIteamranking  where rank=1 ");
             rs.next();
            jLabel24.setText(rs.getString(1)); 
             rs=st.executeQuery("select T20 from T20teamranking  where rank=1 ");
             rs.next();
            jLabel28.setText(rs.getString(1)); 
            
            
        con.close();
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        try
        {
            connection();
            rs=st.executeQuery("select rank,test,rating1 from testbatranking");
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            rs=st.executeQuery("select rank,ODI,rating2 from ODIbatranking");
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
            rs=st.executeQuery("select rank,T20,rating3 from T20batranking");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        
        con.close();
        }
        catch(ClassNotFoundException | SQLException ex) {
            Logger.getLogger(mycricket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try
        {
            connection();
            rs=st.executeQuery("select rank,test,rating1 from testbowlranking");
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            rs=st.executeQuery("select rank,ODI,rating2 from ODIbowlranking");
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
            rs=st.executeQuery("select rank,T20,rating3 from T20bowlranking");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            

            con.close();
        }
        catch(ClassNotFoundException | SQLException ex) {
            Logger.getLogger(mycricket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        opponentfix obj=new opponentfix();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        addplayers obj=new addplayers();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        viewfixture obj=new viewfixture();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
        faq obj=new faq();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        existingteam obj=new existingteam();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton20KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton20KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String op=(String)jComboBox1.getSelectedItem();
        DateFormat formatter; 
        formatter = new SimpleDateFormat("yyyy-MM-dd");
        String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        
                java.util.Date givendate = null;
               
        try {
            givendate = formatter.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(mycricket.class.getName()).log(Level.SEVERE, null, ex);
        }
                
         
        
        try
        {
            connection();
            rs=st.executeQuery("select start,end from opponentfix where opponent='"+op+"'");
            if(rs.next())
            {
                
                String date1=rs.getString("start");
                String date2=rs.getString("end");
                
                        java.util.Date sdate =   formatter.parse(date1);
                        java.util.Date edate =   formatter.parse(date2);
                
                if(sdate.equals(givendate)||edate.equals(givendate))
                {
                    JOptionPane.showMessageDialog(null,"The date is already occupied!");
                }
                else if(givendate.before(edate)&&givendate.after(sdate))
                {
                    JOptionPane.showMessageDialog(null,"The date is already occupied by another fixture!");
                }   
                else 
                {
                    
                    JOptionPane.showMessageDialog(null,"Date you entered is available!");
                    jDateChooser2.setDate(givendate);
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Date you entered is available!");
                 jDateChooser2.setDate(givendate);
            }
           con.close();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         String sql="select opponent as 'Team Name', start as 'Match Strating Date',end as 'Match Ending Date'from opponentfix order by start";
        try
        {
         connection();
            rs= st.executeQuery(sql);
         jTable5.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e)
         {
            JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton36KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton36KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton36KeyPressed

    private void jButton37KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton37KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton37KeyPressed

    private void jButton38KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton38KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton38KeyPressed

    private void jButton40KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton40KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton40KeyPressed

    private void jButton39KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton39KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton39KeyPressed

    private void jButton26KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton26KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton26KeyPressed

    private void jButton32KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton32KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton32KeyPressed

    private void jButton33KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton33KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton33KeyPressed

    private void jButton34KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton34KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
        
    }//GEN-LAST:event_jButton34KeyPressed

    private void jButton35KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton35KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton35KeyPressed

    private void jButton42KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton42KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
          jLabel14.setText(String.valueOf(over1));
        jLabel20.setText(String.valueOf(over2));
        over2=over2+1;
        jLabel20.setText(String.valueOf(over2));
        if(over2==6)
            {
                over1=over1+1;
                jLabel14.setText(String.valueOf(over1));
                over2=0;
            }
         }
    }//GEN-LAST:event_jButton42KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try
       {
           connection();
           int flag=0;
           
           DateFormat formatter; 
           formatter = new SimpleDateFormat("yyyy-MM-dd");
           String op=(String)jComboBox1.getSelectedItem();
           String format=(String)jComboBox2.getSelectedItem();
           String venue=jTextField2.getText();
           String date=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
           java.util.Date givendate = null;
            try
            {
                givendate = formatter.parse(date);
            } 
            catch (ParseException ex)
            {
                Logger.getLogger(mycricket.class.getName()).log(Level.SEVERE, null, ex);
            }
           java.util.Date e1date =givendate;
           rs=st.executeQuery("select start,end from homefix");
           while(rs.next())
           {
               
                String hs=rs.getString(1);
                String he=rs.getString(2);
                       java.util.Date hsdate =   formatter.parse(hs);
                       java.util.Date hedate =   formatter.parse(he);
                       
                       
                if(hsdate.equals(givendate)||hedate.equals(givendate))
                {
                    flag=1;
                }
                if(givendate.before(hedate)&&givendate.after(hsdate))
                {
                    flag=1;
                }
                if((!hsdate.equals(givendate)||!hedate.equals(givendate))&&(!givendate.before(hedate)&&givendate.after(hsdate)))
                {
                    flag=0;
                }
                
                
            }
           if(flag==1)
           {
               JOptionPane.showMessageDialog(null,"The date is already occupied !");
           }
           if(flag==0)
           {
               java.sql.Date sqlStartDate = new java.sql.Date(givendate.getTime()); 
                       java.sql.Date edate = new java.sql.Date(e1date.getTime()); 
              JOptionPane.showMessageDialog(null,"The date is available in home fixture!");
                    if(format.equals("Test"))
                    {
                       
                       st.executeUpdate("insert into homefix values('"+op+"','"+sqlStartDate+"','"+edate+"','"+venue+"','"+format+"')");
                       JOptionPane.showMessageDialog(null,"Fixture organized !");
                       st.executeUpdate("update homefix set end=DATE_ADD(end,INTERVAL 6 DAY) where format='Test'");
                       return;
                    }
                    else if(format.equals("ODI"))
                    {
                       
                       st.executeUpdate("insert into homefix values('"+op+"','"+sqlStartDate+"','"+edate+"','"+venue+"','"+format+"')");
                        JOptionPane.showMessageDialog(null,"Fixture organized !");
                       st.executeUpdate("update homefix set end=DATE_ADD(end,INTERVAL 2 DAY) where format='ODI'");
                       return;
                    }
                    else if(format.equals("T20"))
                    {
                        
                       st.executeUpdate("insert into homefix values('"+op+"','"+sqlStartDate+"','"+edate+"','"+venue+"','"+format+"')");
                        JOptionPane.showMessageDialog(null,"Fixture organized !");
                       st.executeUpdate("update homefix set end=DATE_ADD(end,INTERVAL 2 DAY) where format='T20'");
                       return;
                    }
           }
           con.close();
        }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try
        {
             connection();
             String sql="select opponent as 'Team Name', start as 'Match Starting Date',end as 'Match Ending Date'from homefix order by start";
             rs= st.executeQuery(sql);
             jTable5.setModel(DbUtils.resultSetToTableModel(rs));
             con.close();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycricket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycricket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycricket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycricket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                
                new mycricket().setVisible(true);
                
            }
        });
        
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
/*
class scroll extends JPanel
{
    public void paint(Graphics g)
    {
	int x=0,y=700;
	super.paint(g);
	Graphics2D g2=(Graphics2D)g;
	String s="Developed by Jesseeel Mugdhar,Gautam Panickar SS,Gouri S,Keerthi S";
	Font f=new Font("tahoma",Font.BOLD+Font.PLAIN,18);
	g2.setFont(f);
	g2.setColor(Color.WHITE);
	g2.drawString(s,x,y);
	
	try
	{
		Thread.sleep(100);
	}
	catch(Exception e)
	{
	}
	x+=10;
	if(x>this.getWidth())
	{
		x=0;
	}
	repaint();
    }
    public static void main(String[] args)
    {
        JLabel jl=new JLabel("Scroll");
	jl.setSize(700,200);
	jl.add(new scroll());
	jl.setVisible(true);
    }
}*/